on: ["push", "pull_request"]

env:
  ETHERSCAN_TOKEN: 9MKURTHE8FNA9NRUUJBHMUEVY6IQ5K1EGY
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: 44c6300c5e5b4b2da5fc42b06bf18a8e

name: main workflow

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e lint

  core:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-minor: [6, 7, 8]

    steps:
    - uses: actions/checkout@v2

    - name: Cache Compiler Installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache-${{ matrix.os }}

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Install Ganache
      run: npm install -g ganache-cli@6.12.1

    - name: Setup Python 3.${{ matrix.python-minor }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.${{ matrix.python-minor }}

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e py3${{ matrix.python-minor }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
